seed: ~

model:
  target: src.models.coconut.LitCoconut
  model_kwargs:
    model_id: Qwen3-4B-Instruct
    llm_path: /home/dingxukai/RoT/ckpt/base/Qwen3-4B-Instruct/qwen3-instruct
    sft_method: coconut
    chat_template: False
    trust_remote_code: False
    torch_dtype: bfloat16
    attn_implementation: ~

    do_lora: True
    lora_config:
      r: 64
      lora_alpha: 32
      target_modules:
        - q_proj
        - k_proj
        - v_proj
        - o_proj
        - gate_proj
        - up_proj
        - down_proj

    coconut_config:
      coconut_proj: False
      n_epochs_per_stage: 2
      max_n_stage: 3
      n_latents_per_step: 2
      current_stage: 1

    latent_policy_config:
      lp_determinisitc: False
      lp_intermediate_size: 2048

    answer_generation_config:
      max_new_tokens: 16
      do_sample: True
      top_p: 0.9
      temperature: 1.0

  training_kwargs:
    optimizer:
      target: torch.optim.AdamW
      lr: 3e-5
      weight_decay: 0.01
      foreach: False
    use_scheduler: False
    scheduler:
      target: constant_schedule_with_warmup
      warmup_steps: 1000

trainer:
  max_epochs: 50

dataloader:
  batch_size: 1
  val_batch_size: 1
  num_workers: 4
  pin_memory: True
  persistent_workers: False
