"""Role-native TRACE-BRIDGE trained end to end inside one model lineage.

This model keeps the validated BRIDGE information path: the answer decoder
reads the raw question and all eight causal latent states.  The positions are
not anonymous, however: PLAN, five SOLVE transitions, REFINE, and COMMIT are
generated by a role-conditioned Gaussian policy and receive direct textual-CoT
formation losses.  Stage 2 jointly optimizes latent actions and answer tokens.

No historical TRACE/BRIDGE checkpoint, capability teacher, rewind, memory
bank, hard-negative generator, or counterfactual replacement is used.
"""

import copy
import math
from typing import Dict, List, Optional, Sequence

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils import clip_grad_norm_

from .trace_bridge import LitTRACEBridge
from ..modules import grpo
from ..modules.role_native import (
    COMMIT_INDEX,
    N_ROLES,
    RoleLatentPolicy,
    RoleTargets,
    build_role_targets,
    clipped_policy_loss,
    diagonal_gaussian_kl,
    discounted_role_returns,
    group_standardize,
    masked_cosine_loss,
)


class LitTRACERoleNative(LitTRACEBridge):
    """A complete role-native successor to the strong 72% code path."""

    def init_trace_rl(self):
        """Enable manual optimization without constructing legacy GRPOLoss.

        Native v9 implements its answer-token and latent-action PPO objectives
        directly, so instantiating TRACEBridge's answer-only loss would add an
        unused configuration dependency and obscure the actual objective.
        """
        self.automatic_optimization = False
        self.trace_rl_config = self.model_kwargs.trace_rl_config

    def __init__(self, model_kwargs, training_kwargs, all_config=None):
        # Historical checkpoints are rejected at the orchestration boundary.
        # The model itself contains no modules or arguments that can map one.
        super().__init__(
            model_kwargs=model_kwargs,
            training_kwargs=training_kwargs,
            all_config=all_config,
        )
        self.role_config = model_kwargs.get("role_native_config", {})
        if int(self.readcot_config.n_latents) != N_ROLES:
            raise ValueError("role-native TRACE requires exactly eight latents")
        if self.readcot_config.get("implicit_latent_mode", "block") != "block":
            raise ValueError("role-native TRACE must retain the strong block prior")
        if not bool(self.role_config.get("answer_reads_question", True)):
            raise ValueError("the reliable raw-question information bridge is mandatory")
        if not bool(self.role_config.get("answer_reads_all_roles", True)):
            raise ValueError("native v9 retains all-role readout; COMMIT-only is forbidden")

        self.role_policy = RoleLatentPolicy(
            hidden_size=self.hidden_size,
            action_dim=int(self.role_config.get("action_dim", 16)),
            policy_hidden_size=int(
                self.role_config.get("policy_hidden_size", 512)
            ),
            role_embedding_size=int(
                self.role_config.get("role_embedding_size", 64)
            ),
            initial_log_std=float(
                self.role_config.get("initial_log_std", -0.7)
            ),
        )
        projection_size = int(self.role_config.get("semantic_projection_size", 256))
        generator = torch.Generator(device="cpu")
        generator.manual_seed(1701)
        projection = torch.randn(
            projection_size,
            self.hidden_size,
            generator=generator,
            dtype=torch.float32,
        ) / math.sqrt(self.hidden_size)
        self.register_buffer("role_semantic_projection", projection)
        self.plan_forecaster = nn.Sequential(
            nn.LayerNorm(self.hidden_size),
            nn.Linear(self.hidden_size, 512),
            nn.GELU(),
            nn.Linear(512, 5 * projection_size),
        )
        self.role_action_scale = float(
            self.role_config.get("action_embedding_scale", 0.05)
        )

        # The reference belongs to this run's Stage-1 checkpoint.  It must be
        # created *after* run.py loads that checkpoint; constructing it here
        # would accidentally freeze a random, pre-load policy.
        self.stage1_role_reference = None

    def initialize_stage2_reference_after_load(self):
        """Freeze this run's loaded Stage-1 policy before Trainer/DDP setup."""
        if not self.do_trace_rl:
            raise RuntimeError("a Stage-1 model cannot create an RL reference")
        if self.stage1_role_reference is not None:
            raise RuntimeError("Stage-2 role reference was initialized twice")
        self.stage1_role_reference = copy.deepcopy(self.role_policy).eval()
        for parameter in self.stage1_role_reference.parameters():
            parameter.requires_grad_(False)

    def on_fit_start(self):
        if self.do_trace_rl:
            if self.stage1_role_reference is None:
                raise RuntimeError(
                    "Stage 2 must load and freeze this run's Stage-1 policy "
                    "before Trainer/DDP setup"
                )
        return super().on_fit_start()

    def _question_only_latents(
        self,
        questions: Sequence[str],
        trace_view_ids: Optional[torch.Tensor] = None,
        trace_noise_std: Optional[float] = None,
        trace_latent_noise: Optional[torch.Tensor] = None,
        trace_latent_noise_scale: Optional[float] = None,
        *,
        deterministic_roles: Optional[bool] = None,
        forced_actions: Optional[torch.Tensor] = None,
    ) -> Dict[str, torch.Tensor]:
        """Generate the eight native roles within the original BRIDGE path.

        At zero role action the inputs reduce to the strong block-latent prior.
        Sequential cache updates make every later role causal while the answer
        retains access to the raw question and all role states.
        """
        batch_size = len(questions)
        if deterministic_roles is None:
            # Stage-1 formation, Stage-2 replay, validation, and test must all
            # use the stable mean path.  Only native_role_rollout explicitly
            # requests stochastic actions.
            deterministic_roles = True
        action_dim = self.role_policy.action_dim
        if forced_actions is not None and tuple(forced_actions.shape) != (
            batch_size,
            N_ROLES,
            action_dim,
        ):
            raise ValueError("forced actions have an invalid role-policy shape")

        question_ids, question_mask = self.prepare_inputs(
            list(questions),
            padding_side="left",
            part="question",
            suffix=self.thinking_separator,
        )
        question_embeds = self.embedding(question_ids)
        question_outputs = self.llm.forward(
            inputs_embeds=question_embeds,
            attention_mask=question_mask,
            position_ids=self.make_position_ids_for_current_input(
                question_mask, question_embeds.shape[1]
            ),
            output_hidden_states=True,
            use_cache=True,
        )
        cache = question_outputs.past_key_values
        question_state = self.state_norm(
            question_outputs.hidden_states[-1][:, -1, :]
        )
        previous_state = question_state
        anchor_gate = (
            torch.sigmoid(self.anchor_gate_predictor(question_state))
            if self.use_anchor_gate
            else None
        )

        base = self.latent_bridge(question_state).unsqueeze(1)
        query_scale = float(
            self.readcot_config.get("block_latent_query_scale", 0.1)
        )
        queries = self.step_compressor.latent_queries[:N_ROLES].unsqueeze(0)
        anchored_inputs = base + query_scale * queries.expand(
            batch_size, -1, -1
        ).to(base.dtype)
        if trace_view_ids is not None and hasattr(self, "trace_view_embeddings"):
            view_ids = trace_view_ids.to(self.device).long().remainder(
                self.max_trace_views
            )
            anchored_inputs = anchored_inputs + float(
                self.trace_config.get("trace_view_scale", 0.3)
            ) * self.trace_view_embeddings(view_ids).unsqueeze(1).to(
                anchored_inputs.dtype
            )
            if hasattr(self, "trace_step_view_embeddings"):
                step_ids = torch.arange(N_ROLES, device=self.device)
                table_ids = view_ids.unsqueeze(1) * self.max_trace_latents + step_ids
                anchored_inputs = anchored_inputs + float(
                    self.trace_config.get("trace_step_view_scale", 0.15)
                ) * self.trace_step_view_embeddings(table_ids).to(
                    anchored_inputs.dtype
                )
        if anchor_gate is not None:
            gate_values = anchor_gate[:, :N_ROLES, None].to(anchored_inputs.dtype)
            anchored_inputs = anchored_inputs * (
                1.0
                + float(self.readcot_config.get("anchor_gate_scale", 0.5))
                * gate_values
            )

        if trace_latent_noise is not None:
            if tuple(trace_latent_noise.shape) != tuple(anchored_inputs.shape):
                raise ValueError("trace latent noise has an invalid shape")
            if trace_latent_noise_scale is None:
                trace_latent_noise_scale = float(
                    self.model_kwargs.trace_rl_config.get(
                        "stage2_latent_noise_scale", 0.0
                    )
                )
            anchored_inputs = anchored_inputs + float(
                trace_latent_noise_scale
            ) * trace_latent_noise.to(anchored_inputs)

        context_mask = question_mask
        actual_inputs = []
        states = []
        residuals = []
        actions = []
        action_log_probs = []
        action_means = []
        action_log_stds = []
        pre_action_states = []
        for role_index in range(N_ROLES):
            pre_action_states.append(previous_state)
            action, log_prob, mean, log_std = self.role_policy.realize(
                previous_state,
                role_index,
                deterministic=bool(deterministic_roles),
                forced_action=(
                    None
                    if forced_actions is None
                    else forced_actions[:, role_index]
                ),
            )
            action_residual = self.role_policy.action_projector(action.float())
            current_input = (
                anchored_inputs[:, role_index].float()
                + self.role_action_scale * action_residual
            ).to(question_embeds.dtype)
            current_mask = torch.ones(
                batch_size, 1, device=self.device, dtype=context_mask.dtype
            )
            context_mask = torch.cat([context_mask, current_mask], dim=1)
            outputs = self.llm.forward(
                inputs_embeds=current_input.unsqueeze(1),
                attention_mask=context_mask,
                position_ids=self.make_position_ids_for_current_input(
                    context_mask, 1
                ),
                past_key_values=cache,
                output_hidden_states=True,
                use_cache=True,
            )
            cache = outputs.past_key_values
            current_state = self.state_norm(
                outputs.hidden_states[-1][:, -1, :]
            )
            actual_inputs.append(current_input)
            states.append(current_state)
            residuals.append(current_state - previous_state)
            actions.append(action)
            action_log_probs.append(log_prob)
            action_means.append(mean)
            action_log_stds.append(log_std)
            previous_state = current_state

        latent_inputs = torch.stack(actual_inputs, dim=1)
        latent_mask = torch.ones(
            batch_size, N_ROLES, device=self.device, dtype=question_mask.dtype
        )
        return {
            "question_input_ids": question_ids,
            "question_attention_mask": question_mask,
            "latent_inputs_embeds": latent_inputs,
            "latent_attention_mask": latent_mask,
            "context_inputs_embeds": torch.cat(
                [question_embeds, latent_inputs], dim=1
            ),
            "context_attention_mask": context_mask,
            "past_key_values": cache,
            "implicit_residuals": torch.stack(residuals, dim=1),
            "latent_states": torch.stack(states, dim=1),
            "pre_action_states": torch.stack(pre_action_states, dim=1),
            "role_actions": torch.stack(actions, dim=1),
            "role_action_log_probs": torch.stack(action_log_probs, dim=1),
            "role_action_means": torch.stack(action_means, dim=1),
            "role_action_log_stds": torch.stack(action_log_stds, dim=1),
            "anchor_gate": anchor_gate,
            "trace_view_ids": trace_view_ids,
        }

    def _project_solve_targets(self, targets: torch.Tensor) -> torch.Tensor:
        return F.linear(targets.float(), self.role_semantic_projection.float())

    def _role_loss_components(
        self,
        latent_outputs: Dict[str, torch.Tensor],
        targets: RoleTargets,
    ) -> Dict[str, torch.Tensor]:
        states = latent_outputs["latent_states"]
        residuals = latent_outputs["implicit_residuals"]
        batch_size = states.shape[0]
        projection_size = self.role_semantic_projection.shape[0]
        plan_forecast = self.plan_forecaster(states[:, 0]).reshape(
            batch_size, 5, projection_size
        )
        plan_loss = masked_cosine_loss(
            plan_forecast,
            self._project_solve_targets(targets.solve),
            targets.solve_mask,
        )
        solve_loss = masked_cosine_loss(
            residuals[:, 1:6].float(),
            targets.solve,
            targets.solve_mask,
        )
        active = torch.ones(batch_size, device=self.device, dtype=torch.bool)
        refine_loss = masked_cosine_loss(
            residuals[:, 6].float(), targets.refine, active
        )
        commit_loss = masked_cosine_loss(
            states[:, 7].float(), targets.commit, active
        )
        std = torch.exp(latent_outputs["role_action_log_stds"][:, :7].float())
        minimum_std = float(self.role_config.get("minimum_action_std", 0.12))
        entropy_floor = F.relu(minimum_std - std).mean()
        return {
            "plan": plan_loss,
            "solve": solve_loss,
            "refine": refine_loss,
            "commit": commit_loss,
            "entropy_floor": entropy_floor,
        }

    def _native_role_training_losses(
        self,
        *,
        explicit_features,
        compression_outputs,
        latent_outputs,
    ) -> Dict[str, torch.Tensor]:
        del compression_outputs
        targets = build_role_targets(explicit_features)
        components = self._role_loss_components(latent_outputs, targets)
        weights = {
            "plan": float(self.role_config.get("stage1_plan_weight", 0.08)),
            "solve": float(self.role_config.get("stage1_solve_weight", 0.12)),
            "refine": float(self.role_config.get("stage1_refine_weight", 0.06)),
            "commit": float(self.role_config.get("stage1_commit_weight", 0.10)),
            "entropy_floor": float(
                self.role_config.get("stage1_entropy_floor_weight", 0.002)
            ),
        }
        total = sum(weights[name] * value for name, value in components.items())
        return {
            "role_total_loss": total,
            "role_plan_loss": components["plan"],
            "role_solve_loss": components["solve"],
            "role_refine_loss": components["refine"],
            "role_commit_loss": components["commit"],
            "role_entropy_floor_loss": components["entropy_floor"],
        }

    def _collect_role_targets_from_batch(self, batch) -> RoleTargets:
        explicit_features = self._collect_explicit_batch_features(
            questions=batch["question"],
            step_lists=self._decode_step_lists(batch),
            answers=batch["answer"],
            dependency_matrices=self._decode_cached_matrices(
                batch, "dependency_matrix"
            ),
            confidence_matrices=self._decode_cached_matrices(
                batch, "confidence_matrix"
            ),
        )
        return build_role_targets(explicit_features)

    def _generate_from_role_outputs(
        self,
        latent_outputs: Dict[str, torch.Tensor],
        *,
        do_sample: bool,
    ) -> torch.Tensor:
        batch_size = latent_outputs["latent_states"].shape[0]
        end_ids = torch.full(
            (batch_size, 1),
            self.thinking_separator_id,
            device=self.device,
            dtype=torch.long,
        )
        pieces = [latent_outputs["context_inputs_embeds"], self.embedding(end_ids)]
        masks = [latent_outputs["context_attention_mask"], torch.ones_like(end_ids)]
        if self.readcot_config.get("hybrid_seed_anchor_header", False):
            prefix_ids, prefix_mask = self._prepare_raw_texts(
                [self.anchor_header + "\n"] * batch_size,
                padding_side="right",
            )
            pieces.append(self.embedding(prefix_ids))
            masks.append(prefix_mask)
        generation = dict(self._get_generation_config())
        generation["do_sample"] = bool(do_sample)
        if do_sample:
            generation["temperature"] = float(
                self.trace_rl_config.get("temperature", 0.95)
            )
            generation["top_p"] = float(self.trace_rl_config.get("top_p", 0.97))
        return self.llm.generate(
            inputs_embeds=torch.cat(pieces, dim=1),
            attention_mask=torch.cat(masks, dim=1),
            **generation,
        )

    def _answer_logprobs_from_role_outputs(
        self,
        latent_outputs: Dict[str, torch.Tensor],
        answer_ids: torch.Tensor,
        answer_mask: torch.Tensor,
    ) -> torch.Tensor:
        batch_size = answer_ids.shape[0]
        prompt_ids, prompt_mask = self._prompt_ids_for_generated_answer(batch_size)
        prompt_embeds = self.embedding(prompt_ids)
        answer_embeds = self.embedding(answer_ids)
        inputs = torch.cat(
            [latent_outputs["context_inputs_embeds"], prompt_embeds, answer_embeds],
            dim=1,
        )
        mask = torch.cat(
            [latent_outputs["context_attention_mask"], prompt_mask, answer_mask],
            dim=1,
        )
        outputs = self.llm.forward(
            inputs_embeds=inputs,
            attention_mask=mask,
            position_ids=self.make_position_ids_for_current_input(mask, inputs.shape[1]),
            output_hidden_states=False,
        )
        start = latent_outputs["context_inputs_embeds"].shape[1] + prompt_ids.shape[1] - 1
        logits = outputs.logits[:, start : start + answer_ids.shape[1]]
        selected = F.log_softmax(logits.float(), dim=-1).gather(
            -1, answer_ids.unsqueeze(-1)
        ).squeeze(-1)
        return torch.nan_to_num(selected, nan=-30.0, neginf=-30.0).clamp(-30.0, 30.0)

    def _role_step_scores(
        self,
        latent_outputs: Dict[str, torch.Tensor],
        targets: RoleTargets,
    ) -> torch.Tensor:
        states = latent_outputs["latent_states"]
        residuals = latent_outputs["implicit_residuals"]
        scores = states.new_zeros(states.shape[0], N_ROLES).float()
        projection_size = self.role_semantic_projection.shape[0]
        forecast = self.plan_forecaster(states[:, 0]).reshape(
            states.shape[0], 5, projection_size
        )
        plan_scores = F.cosine_similarity(
            forecast.float(), self._project_solve_targets(targets.solve), dim=-1
        )
        solve_weights = targets.solve_mask.float()
        scores[:, 0] = (plan_scores * solve_weights).sum(-1) / solve_weights.sum(
            -1
        ).clamp_min(1.0)
        scores[:, 1:6] = F.cosine_similarity(
            residuals[:, 1:6].float(), targets.solve.float(), dim=-1
        ) * solve_weights
        scores[:, 6] = F.cosine_similarity(
            residuals[:, 6].float(), targets.refine.float(), dim=-1
        )
        scores[:, 7] = F.cosine_similarity(
            states[:, 7].float(), targets.commit.float(), dim=-1
        )
        return scores

    @staticmethod
    def _pad_2d(rows: List[torch.Tensor], fill: float) -> torch.Tensor:
        width = max(row.shape[1] for row in rows)
        padded = []
        for row in rows:
            if row.shape[1] == width:
                padded.append(row)
            else:
                tail = torch.full(
                    (row.shape[0], width - row.shape[1]),
                    fill,
                    device=row.device,
                    dtype=row.dtype,
                )
                padded.append(torch.cat([row, tail], dim=1))
        return torch.cat(padded, dim=0)

    @torch.no_grad()
    def native_role_rollout(self, batch) -> Dict[str, object]:
        group_size = int(self.trace_rl_config.get("group_size", 8))
        if group_size != 8:
            raise ValueError("the formal native-role run uses group_size=8")
        questions = list(batch["question"])
        answers = list(batch["answer"])
        base_targets = self._collect_role_targets_from_batch(batch)
        group_questions = []
        group_answers = []
        actions = []
        old_role_log_probs = []
        answer_rows = []
        answer_mask_rows = []
        old_answer_logprob_rows = []
        accuracies = []
        step_scores = []
        target_indices = []

        for sample_index, (question, answer) in enumerate(zip(questions, answers)):
            for _ in range(group_size):
                outputs = self._question_only_latents(
                    [question], deterministic_roles=False
                )
                generated = self._generate_from_role_outputs(
                    outputs, do_sample=True
                )
                mask = generated.ne(self.tokenizer.pad_token_id).long()
                old_answer = self._answer_logprobs_from_role_outputs(
                    outputs, generated, mask
                )
                text = self.tokenizer.decode(
                    generated[0], skip_special_tokens=True
                )
                prediction = self.extract_answer_from_output(text)
                accuracy = float(
                    self.verify_answer(gt_answer=answer, pred_answer=prediction)
                )
                target = RoleTargets(
                    solve=base_targets.solve[sample_index : sample_index + 1],
                    solve_mask=base_targets.solve_mask[
                        sample_index : sample_index + 1
                    ],
                    refine=base_targets.refine[sample_index : sample_index + 1],
                    commit=base_targets.commit[sample_index : sample_index + 1],
                )
                group_questions.append(question)
                group_answers.append(answer)
                target_indices.append(sample_index)
                actions.append(outputs["role_actions"])
                old_role_log_probs.append(outputs["role_action_log_probs"])
                answer_rows.append(generated)
                answer_mask_rows.append(mask)
                old_answer_logprob_rows.append(old_answer)
                accuracies.append(accuracy)
                step_scores.append(self._role_step_scores(outputs, target))

        accuracy_tensor = torch.tensor(
            accuracies, device=self.device, dtype=torch.float32
        )
        terminal_advantages = []
        for start in range(0, len(accuracies), group_size):
            terminal_advantages.append(
                grpo.group_advantages(
                    accuracy_tensor[start : start + group_size]
                )
            )
        terminal_advantages = torch.cat(terminal_advantages, dim=0)
        scores = torch.cat(step_scores, dim=0)
        local_returns = discounted_role_returns(
            scores,
            gamma=float(self.trace_rl_config.get("step_reward_discount", 0.9)),
        )
        local_advantages = group_standardize(local_returns, group_size)
        role_advantages = terminal_advantages[:, None] + float(
            self.trace_rl_config.get("step_reward_weight", 0.15)
        ) * local_advantages
        return {
            "questions": group_questions,
            "answers": group_answers,
            "target_indices": target_indices,
            "base_targets": base_targets,
            "actions": torch.cat(actions, dim=0).float(),
            "old_role_log_probs": torch.cat(old_role_log_probs, dim=0).float(),
            "answer_ids": self._pad_2d(
                answer_rows, float(self.tokenizer.pad_token_id)
            ).long(),
            "answer_mask": self._pad_2d(answer_mask_rows, 0.0).long(),
            "old_answer_log_probs": self._pad_2d(
                old_answer_logprob_rows, 0.0
            ).float(),
            "accuracies": accuracy_tensor,
            "terminal_advantages": terminal_advantages.float(),
            "role_advantages": role_advantages.float(),
            "step_scores": scores,
        }

    def _reference_role_kl(
        self,
        pre_action_states: torch.Tensor,
    ) -> torch.Tensor:
        if self.stage1_role_reference is None:
            raise RuntimeError("Stage-2 reference policy was not initialized")
        terms = []
        for role_index in range(COMMIT_INDEX):
            current_mean, current_log_std = self.role_policy.distribution(
                pre_action_states[:, role_index], role_index
            )
            with torch.no_grad():
                reference_mean, reference_log_std = (
                    self.stage1_role_reference.distribution(
                        pre_action_states[:, role_index], role_index
                    )
                )
            terms.append(
                diagonal_gaussian_kl(
                    current_mean.float(),
                    current_log_std.float(),
                    reference_mean.float(),
                    reference_log_std.float(),
                )
            )
        return torch.stack(terms, dim=1).mean()

    def trace_rl_training_step(self, batch, batch_idx, dataloader_idx=0):
        del batch_idx, dataloader_idx
        optimizer = self.optimizers()
        rollout = self.native_role_rollout(batch)
        # Rollout is inference-only and can leave large, variably-sized CUDA
        # blocks in the caching allocator.  Release those blocks before the
        # differentiable PPO/replay passes.  This does not touch live tensors
        # or accumulated gradients and keeps the Stage-2 objective unchanged.
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        optimizer.zero_grad()
        total_items = len(rollout["questions"])
        answer_sum = torch.zeros((), device=self.device)
        latent_sum = torch.zeros((), device=self.device)
        kl_sum = torch.zeros((), device=self.device)
        entropy_sum = torch.zeros((), device=self.device)
        role_mask = torch.ones(1, N_ROLES, device=self.device, dtype=torch.bool)
        role_mask[:, COMMIT_INDEX] = False
        clip = float(self.trace_rl_config.get("trajectory_clip_epsilon", 0.12))
        latent_weight = float(self.trace_rl_config.get("latent_policy_weight", 1.0))
        answer_weight = float(self.trace_rl_config.get("answer_policy_weight", 1.0))
        kl_weight = float(self.trace_rl_config.get("stage1_policy_kl_weight", 0.02))
        entropy_weight = float(self.trace_rl_config.get("entropy_coefficient", 0.001))

        for index, question in enumerate(rollout["questions"]):
            outputs = self._question_only_latents(
                [question],
                deterministic_roles=False,
                forced_actions=rollout["actions"][index : index + 1],
            )
            current_answer_log_probs = self._answer_logprobs_from_role_outputs(
                outputs,
                rollout["answer_ids"][index : index + 1],
                rollout["answer_mask"][index : index + 1],
            )
            answer_loss = self._ppo_answer_loss(
                current_answer_log_probs,
                rollout["old_answer_log_probs"][index : index + 1],
                rollout["answer_mask"][index : index + 1].float(),
                rollout["terminal_advantages"][index : index + 1, None],
            )
            latent_loss = clipped_policy_loss(
                outputs["role_action_log_probs"].float(),
                rollout["old_role_log_probs"][index : index + 1],
                rollout["role_advantages"][index : index + 1],
                role_mask,
                clip,
            )
            role_kl = self._reference_role_kl(outputs["pre_action_states"])
            entropy = (
                outputs["role_action_log_stds"][:, :COMMIT_INDEX].float()
                + 0.5 * math.log(2.0 * math.pi * math.e)
            ).sum(dim=-1).mean()
            objective = (
                answer_weight * answer_loss
                + latent_weight * latent_loss
                + kl_weight * role_kl
                - entropy_weight * entropy
            )
            self.manual_backward(objective / float(total_items))
            answer_sum += answer_loss.detach()
            latent_sum += latent_loss.detach()
            kl_sum += role_kl.detach()
            entropy_sum += entropy.detach()
            # Backward has consumed this independent per-trajectory graph.
            # Do not retain the final trajectory while constructing the much
            # larger supervised-replay graph below.
            del (
                outputs,
                current_answer_log_probs,
                answer_loss,
                latent_loss,
                role_kl,
                entropy,
                objective,
            )

        replay_weight = float(
            self.trace_rl_config.get("stage2_sft_replay_weight", 0.05)
        )
        replay = torch.zeros((), device=self.device)
        if replay_weight > 0:
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            replay = self.forward(batch)["total_loss"]
            # The forward graph remains live; only fragmented, unused cached
            # blocks are returned so replay backward has contiguous headroom.
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            self.manual_backward(replay_weight * replay)
        grad_norm = clip_grad_norm_(
            self.parameters(),
            max_norm=float(self.trace_rl_config.get("clip_grad_norm", 1.0)),
        )
        if not torch.isfinite(grad_norm):
            optimizer.zero_grad(set_to_none=True)
            raise RuntimeError("non-finite gradient in native role Stage 2")
        optimizer.step()
        scheduler = self.lr_schedulers()
        if scheduler is not None:
            scheduler.step()

        denominator = float(total_items)
        total_loss = (
            answer_weight * answer_sum / denominator
            + latent_weight * latent_sum / denominator
            + kl_weight * kl_sum / denominator
            - entropy_weight * entropy_sum / denominator
            + replay_weight * replay.detach()
        )
        logs = {
            "train/total_loss": total_loss,
            "train/answer_policy_loss": answer_sum / denominator,
            "train/latent_policy_loss": latent_sum / denominator,
            "train/stage1_role_kl": kl_sum / denominator,
            "train/role_entropy": entropy_sum / denominator,
            "train/sft_replay_loss": replay.detach(),
            "train/exact_accuracy": rollout["accuracies"].mean(),
            "train/role_step_reward": rollout["step_scores"][:, :7].mean(),
            "train/grad_norm": grad_norm.detach(),
        }
        self.log_dict(logs, sync_dist=True, prog_bar=True, batch_size=len(batch["idx"]))
        return total_loss.detach()
