#!/usr/bin/env bash
set -euo pipefail

GPU="${1:?Usage: bash scripts/trace_auto_mixed_after_sessions.sh <gpu> <sft_ckpt> [wait_sessions_csv] [post_gpu] [post_samples]}"
SFT_CKPT="${2:?Usage: bash scripts/trace_auto_mixed_after_sessions.sh <gpu> <sft_ckpt> [wait_sessions_csv] [post_gpu] [post_samples]}"
WAIT_SESSIONS_CSV="${3:-}"
POST_GPU="${4:-${GPU}}"
POST_SAMPLES="${5:-32}"

ROOT="/disk1/dingxukai/trace_colar"
RUN_OUTPUTS="${ROOT}/run_outputs/trace"
WATCH_SESSION="${WATCH_SESSION:-trace_auto_mixed_after_gpu${GPU}}"
MIXED_SESSION="${MIXED_SESSION:-trace_v2_rl_qwen3_c5_mixed_gpu${GPU}}"

GROUP_SIZE="${GROUP_SIZE:-4}"
EXP_BATCH_SIZE="${EXP_BATCH_SIZE:-1}"
N_TRAIN_SAMPLES="${N_TRAIN_SAMPLES:-128}"
MAX_EPOCHS="${MAX_EPOCHS:-1}"
MAX_N_LATENT_FORWARD="${MAX_N_LATENT_FORWARD:-64}"
TRACE_REWARD_WEIGHT="${TRACE_REWARD_WEIGHT:-0.1}"
LR="${LR:-1e-6}"
LATENT_TEMPERATURE="${LATENT_TEMPERATURE:-1.0}"
TRACE_CENTER_TRAJECTORIES="${TRACE_CENTER_TRAJECTORIES:-True}"
TRACE_FILTER_CANDIDATE_FACTOR="${TRACE_FILTER_CANDIDATE_FACTOR:-1.0}"
TRACE_FILTER_CANDIDATE_COUNT="${TRACE_FILTER_CANDIDATE_COUNT:-128}"
TRACE_FILTER_BATCH_SIZE="${TRACE_FILTER_BATCH_SIZE:-1}"
TRACE_FILTER_MIXED_FILL_FRACTION="${TRACE_FILTER_MIXED_FILL_FRACTION:-0.75}"
ANSWER_TRACE_FILTER_MIXED="${ANSWER_TRACE_FILTER_MIXED:-True}"
ANSWER_TRACE_RESAMPLE_MIXED="${ANSWER_TRACE_RESAMPLE_MIXED:-False}"
ANSWER_TRACE_RESAMPLE_MIXED_MAX_ATTEMPTS="${ANSWER_TRACE_RESAMPLE_MIXED_MAX_ATTEMPTS:-4}"
ANSWER_TRACE_RESAMPLE_MIXED_TARGET_FRAC="${ANSWER_TRACE_RESAMPLE_MIXED_TARGET_FRAC:-1.0}"

mkdir -p "${RUN_OUTPUTS}"

if tmux has-session -t "${WATCH_SESSION}" 2>/dev/null; then
  echo "${WATCH_SESSION} already exists."
  exit 0
fi

tmux new-session -d -s "${WATCH_SESSION}" \
  "set -euo pipefail; \
   cd '${ROOT}'; \
   IFS=',' read -r -a WAIT_SESSIONS <<< '${WAIT_SESSIONS_CSV}'; \
   echo '[TRACE mixed-auto] waiting for sessions: ${WAIT_SESSIONS_CSV}' | tee -a '${RUN_OUTPUTS}/${WATCH_SESSION}.log'; \
   while true; do \
     any_alive=0; \
     for sess in \"\${WAIT_SESSIONS[@]}\"; do \
       if [ -n \"\${sess}\" ] && tmux has-session -t \"\${sess}\" 2>/dev/null; then any_alive=1; fi; \
     done; \
     if [ \"\${any_alive}\" = 0 ]; then break; fi; \
     sleep 300; \
   done; \
   echo '[TRACE mixed-auto] launching mixed-filter v2 ${MIXED_SESSION} on GPU ${GPU}' | tee -a '${RUN_OUTPUTS}/${WATCH_SESSION}.log'; \
   SESSION_NAME='${MIXED_SESSION}' GROUP_SIZE='${GROUP_SIZE}' EXP_BATCH_SIZE='${EXP_BATCH_SIZE}' N_TRAIN_SAMPLES='${N_TRAIN_SAMPLES}' MAX_EPOCHS='${MAX_EPOCHS}' MAX_N_LATENT_FORWARD='${MAX_N_LATENT_FORWARD}' TRACE_REWARD_WEIGHT='${TRACE_REWARD_WEIGHT}' LR='${LR}' LATENT_TEMPERATURE='${LATENT_TEMPERATURE}' TRACE_CENTER_TRAJECTORIES='${TRACE_CENTER_TRAJECTORIES}' TRACE_FILTER_MIXED=True TRACE_FILTER_CANDIDATE_FACTOR='${TRACE_FILTER_CANDIDATE_FACTOR}' TRACE_FILTER_CANDIDATE_COUNT='${TRACE_FILTER_CANDIDATE_COUNT}' TRACE_FILTER_BATCH_SIZE='${TRACE_FILTER_BATCH_SIZE}' TRACE_FILTER_MIXED_FILL_FRACTION='${TRACE_FILTER_MIXED_FILL_FRACTION}' bash scripts/trace_train_v2_rl.sh '${GPU}' '${SFT_CKPT}'; \
   GROUP_SIZE='${GROUP_SIZE}' EXP_BATCH_SIZE='${EXP_BATCH_SIZE}' N_TRAIN_SAMPLES='${N_TRAIN_SAMPLES}' MAX_EPOCHS='${MAX_EPOCHS}' MAX_N_LATENT_FORWARD='${MAX_N_LATENT_FORWARD}' LR='${LR}' LATENT_TEMPERATURE='${LATENT_TEMPERATURE}' TRACE_FILTER_MIXED='${ANSWER_TRACE_FILTER_MIXED}' TRACE_FILTER_CANDIDATE_FACTOR='${TRACE_FILTER_CANDIDATE_FACTOR}' TRACE_FILTER_CANDIDATE_COUNT='${TRACE_FILTER_CANDIDATE_COUNT}' TRACE_FILTER_BATCH_SIZE='${TRACE_FILTER_BATCH_SIZE}' TRACE_FILTER_MIXED_FILL_FRACTION='${TRACE_FILTER_MIXED_FILL_FRACTION}' ANSWER_TRACE_RESAMPLE_MIXED='${ANSWER_TRACE_RESAMPLE_MIXED}' ANSWER_TRACE_RESAMPLE_MIXED_MAX_ATTEMPTS='${ANSWER_TRACE_RESAMPLE_MIXED_MAX_ATTEMPTS}' ANSWER_TRACE_RESAMPLE_MIXED_TARGET_FRAC='${ANSWER_TRACE_RESAMPLE_MIXED_TARGET_FRAC}' bash scripts/trace_auto_answer_after_v2.sh '${MIXED_SESSION}' '${GPU}' '${SFT_CKPT}' '${POST_GPU}' '${POST_SAMPLES}'; \
   echo '[TRACE mixed-auto] mixed watcher launched' | tee -a '${RUN_OUTPUTS}/${WATCH_SESSION}.log'"

echo "Started ${WATCH_SESSION}"
