data_module:
  target: src.datasets.qsa.QSADataModule
  
  # kwargs:
  dataset_name: gsm
  dataset_dir: ${oc.env:TRACE_DATA_ROOT}/GSM8k-Aug-NL/readcot_qsa_qwen_dc
  tiny_dataset: False
  epoch_scaling: 1
